import bs58 from 'bs58';
import { describe, it, expect } from 'vitest';
import { validateConfig } from '../../src/environment';

const VALID_HEX = 'a'.repeat(64);
const VALID_SOLANA = bs58.encode(new Uint8Array(64));
const VALID_SOLANA_ADDRESS = bs58.encode(new Uint8Array(32));

const NON_ELISYM_ENV_KEYS = ['SECRET_SALT', 'ELIZA_SERVER_AUTH_TOKEN'] as const;

const MIN_PROVIDER = {
  ELISYM_PROVIDER_CAPABILITIES: 'summarization',
  ELISYM_PROVIDER_PRICE: '0.001',
} as const;

function envless<T>(fn: () => T, overrides?: Record<string, string | undefined>): T {
  const snapshot: Record<string, string | undefined> = {};
  for (const key of Object.keys(process.env)) {
    if (key.startsWith('ELISYM_')) {
      snapshot[key] = process.env[key];
      delete process.env[key];
    }
  }
  for (const key of NON_ELISYM_ENV_KEYS) {
    snapshot[key] = process.env[key];
    delete process.env[key];
  }
  if (overrides) {
    for (const [key, value] of Object.entries(overrides)) {
      if (value === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = value;
      }
    }
  }
  if (
    process.env.ELISYM_ALLOW_UNSECURED_RUNTIME === undefined &&
    !Object.prototype.hasOwnProperty.call(overrides ?? {}, 'ELISYM_ALLOW_UNSECURED_RUNTIME')
  ) {
    process.env.ELISYM_ALLOW_UNSECURED_RUNTIME = 'true';
  }
  try {
    return fn();
  } finally {
    for (const [key, value] of Object.entries(snapshot)) {
      if (value !== undefined) {
        process.env[key] = value;
      } else {
        delete process.env[key];
      }
    }
    delete process.env.ELISYM_ALLOW_UNSECURED_RUNTIME;
  }
}

describe('validateConfig', () => {
  it('accepts a minimal provider config', () => {
    const cfg = envless(() =>
      validateConfig({
        ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
        ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
        ...MIN_PROVIDER,
      }),
    );
    expect(cfg.network).toBe('devnet');
    expect(cfg.providerCapabilities).toEqual(['summarization']);
    expect(cfg.providerPriceSubunits).toBe(1_000_000n);
    expect(cfg.providerPriceAsset?.token).toBe('sol');
    expect(cfg.providerPriceAsset?.symbol).toBe('SOL');
    expect(cfg.nostrPrivateKeyHex).toBe(VALID_HEX);
  });

  it('accepts a missing Solana private key (auto-generated by WalletService)', () => {
    const cfg = envless(() =>
      validateConfig({
        ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
        ...MIN_PROVIDER,
      }),
    );
    expect(cfg.solanaPrivateKeyBase58).toBeUndefined();
    expect(cfg.nostrPrivateKeyHex).toBe(VALID_HEX);
  });

  it('accepts a missing Nostr private key (auto-generated by ElisymService)', () => {
    const cfg = envless(() => validateConfig({ ...MIN_PROVIDER }));
    expect(cfg.nostrPrivateKeyHex).toBeUndefined();
    expect(cfg.solanaPrivateKeyBase58).toBeUndefined();
  });

  it('rejects an invalid Nostr hex key', () => {
    expect(() =>
      envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: 'zz',
          ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
          ...MIN_PROVIDER,
        }),
      ),
    ).toThrow();
  });

  it('rejects a too-short Solana key', () => {
    expect(() =>
      envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SOLANA_PRIVATE_KEY: bs58.encode(new Uint8Array(32)),
          ...MIN_PROVIDER,
        }),
      ),
    ).toThrow(/64-byte secret/);
  });

  it('requires a provider product, capabilities+price, or skills dir', () => {
    expect(() =>
      envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
        }),
      ),
    ).toThrow(/Provider requires/);
  });

  it('accepts a full provider config', () => {
    const cfg = envless(() =>
      validateConfig({
        ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
        ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
        ELISYM_PROVIDER_CAPABILITIES: 'summarization, text/summarize',
        ELISYM_PROVIDER_PRICE: '0.002',
        ELISYM_PROVIDER_ACTION_MAP: '{"summarization":"SUMMARIZE_TEXT"}',
      }),
    );
    expect(cfg.providerCapabilities).toEqual(['summarization', 'text/summarize']);
    expect(cfg.providerPriceSubunits).toBe(2_000_000n);
    expect(cfg.providerPriceAsset?.token).toBe('sol');
    expect(cfg.providerActionMap).toEqual({ summarization: 'SUMMARIZE_TEXT' });
  });

  it('defaults signerKind to "local"', () => {
    const cfg = envless(() =>
      validateConfig({ ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX, ...MIN_PROVIDER }),
    );
    expect(cfg.signerKind).toBe('local');
  });

  it('accepts signerKind=kms when no plaintext key is configured', () => {
    const cfg = envless(() =>
      validateConfig({
        ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
        ELISYM_SIGNER_KIND: 'kms',
        ...MIN_PROVIDER,
      }),
    );
    expect(cfg.signerKind).toBe('kms');
  });

  it('rejects signerKind=kms paired with a plaintext Solana key', () => {
    expect(() =>
      envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
          ELISYM_SIGNER_KIND: 'kms',
          ...MIN_PROVIDER,
        }),
      ),
    ).toThrow(/ELISYM_SIGNER_KIND must be/);
  });

  it('rejects an unknown signerKind', () => {
    expect(() =>
      envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SIGNER_KIND: 'hardware',
          ...MIN_PROVIDER,
        }),
      ),
    ).toThrow();
  });

  describe('public-only payment address', () => {
    it('accepts ELISYM_SOLANA_PAYMENT_ADDRESS without a private key', () => {
      const cfg = envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SOLANA_PAYMENT_ADDRESS: VALID_SOLANA_ADDRESS,
          ...MIN_PROVIDER,
        }),
      );
      expect(cfg.solanaPaymentAddress).toBe(VALID_SOLANA_ADDRESS);
      expect(cfg.solanaPrivateKeyBase58).toBeUndefined();
    });

    it('rejects ELISYM_SOLANA_PAYMENT_ADDRESS paired with ELISYM_SOLANA_PRIVATE_KEY', () => {
      expect(() =>
        envless(() =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ELISYM_SOLANA_PAYMENT_ADDRESS: VALID_SOLANA_ADDRESS,
            ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
            ...MIN_PROVIDER,
          }),
        ),
      ).toThrow(/mutually exclusive/);
    });

    it('rejects an invalid Solana address (wrong byte length)', () => {
      expect(() =>
        envless(() =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ELISYM_SOLANA_PAYMENT_ADDRESS: bs58.encode(new Uint8Array(16)),
            ...MIN_PROVIDER,
          }),
        ),
      ).toThrow();
    });

    it('rejects a non-base58 Solana address', () => {
      expect(() =>
        envless(() =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ELISYM_SOLANA_PAYMENT_ADDRESS: 'not-a-base58-address!!!@@@##',
            ...MIN_PROVIDER,
          }),
        ),
      ).toThrow();
    });
  });

  describe('single-product vs PRODUCTS conflict', () => {
    const VALID_PROVIDER_PRODUCTS = JSON.stringify([
      {
        name: 'Echo',
        description: 'Echoes input',
        capabilities: ['echo'],
        price: '0.001',
        token: 'sol',
      },
    ]);

    it('throws when both single-product vars and PRODUCTS are set', () => {
      expect(() =>
        envless(() =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
            ELISYM_PROVIDER_PRODUCTS: VALID_PROVIDER_PRODUCTS,
            ELISYM_PROVIDER_CAPABILITIES: 'echo',
            ELISYM_PROVIDER_PRICE: '0.001',
          }),
        ),
      ).toThrow(/conflicts with the single-product vars/);
    });

    it('accepts single-product vars as a first-class configuration', () => {
      const cfg = envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
          ELISYM_PROVIDER_CAPABILITIES: 'echo',
          ELISYM_PROVIDER_PRICE: '0.001',
        }),
      );
      expect(cfg.providerCapabilities).toEqual(['echo']);
      expect(cfg.providerProducts).toBeUndefined();
    });
  });

  describe('server hardening', () => {
    it('refuses mainnet without SECRET_SALT', () => {
      expect(() =>
        envless(
          () =>
            validateConfig({
              ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
              ELISYM_NETWORK: 'mainnet',
              ...MIN_PROVIDER,
            }),
          {
            ELIZA_SERVER_AUTH_TOKEN: 'production-token',
            ELISYM_ALLOW_UNSECURED_RUNTIME: undefined,
          },
        ),
      ).toThrow(/SECRET_SALT/);
    });

    it('refuses mainnet without auth token', () => {
      expect(() =>
        envless(
          () =>
            validateConfig({
              ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
              ELISYM_NETWORK: 'mainnet',
              ...MIN_PROVIDER,
            }),
          { SECRET_SALT: 'a-real-secret-value', ELISYM_ALLOW_UNSECURED_RUNTIME: undefined },
        ),
      ).toThrow(/ELIZA_SERVER_AUTH_TOKEN/);
    });

    it('rejects placeholder SECRET_SALT values', () => {
      expect(() =>
        envless(
          () =>
            validateConfig({
              ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
              ELISYM_NETWORK: 'mainnet',
              ...MIN_PROVIDER,
            }),
          {
            SECRET_SALT: 'changeme',
            ELIZA_SERVER_AUTH_TOKEN: 'real-token',
            ELISYM_ALLOW_UNSECURED_RUNTIME: undefined,
          },
        ),
      ).toThrow(/SECRET_SALT/);
    });

    it('passes mainnet when both SECRET_SALT and auth token are set', () => {
      const cfg = envless(
        () =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ELISYM_NETWORK: 'mainnet',
            ...MIN_PROVIDER,
          }),
        {
          SECRET_SALT: 'a-real-secret-value',
          ELIZA_SERVER_AUTH_TOKEN: 'real-token',
          ELISYM_ALLOW_UNSECURED_RUNTIME: undefined,
        },
      );
      expect(cfg.network).toBe('mainnet');
    });

    it('refuses provider-with-key on devnet without SECRET_SALT', () => {
      expect(() =>
        envless(
          () =>
            validateConfig({
              ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
              ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
              ...MIN_PROVIDER,
            }),
          { ELIZA_SERVER_AUTH_TOKEN: 'real-token', ELISYM_ALLOW_UNSECURED_RUNTIME: undefined },
        ),
      ).toThrow(/SECRET_SALT/);
    });

    it('downgrades the error to a WARN when ELISYM_ALLOW_UNSECURED_RUNTIME=true', () => {
      const cfg = envless(
        () =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ELISYM_NETWORK: 'mainnet',
            ...MIN_PROVIDER,
          }),
        { ELISYM_ALLOW_UNSECURED_RUNTIME: 'true' },
      );
      expect(cfg.network).toBe('mainnet');
    });

    it('does not require hardening when no provider secret key is set on devnet', () => {
      const cfg = envless(
        () =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ...MIN_PROVIDER,
          }),
        {},
      );
      expect(cfg.solanaPrivateKeyBase58).toBeUndefined();
      expect(cfg.network).toBe('devnet');
    });
  });
});
